#include <linux/module.h>			// TODOS LOS MODULOS NECESITAN ESTA LIBRERIA
#include <linux/kernel.h>			// OFRECE LA MACRO KERN_ALERT
#include <linux/init.h>				// OFRECE LA MACRO DE INCIO Y FIN DEL MODULO

static int __init unanzacorestart(void){
	printk(KERN_ALERT "Starting Core0xF0013");					// TEXTO QUE SE MOSTRARA COMO INFORMACION AL USAR ESTA FUNCION
	printk(KERN_ALERT "THANK YOU FOR INSTALLING THIS MODULE");	// TEXTO QUE SE MOSTRARA COMO INFORMACION AL USAR ESTA FUNCION
	return 0;
	// SI ESTE RETURN NO DEVUELVE EL NUMERO 0, ES DEBIDO A UN FALLO AL CARGAR EL MODULO. SI DEVUEVE EL NUMERO 0 ESTA TODO CORRECTO
}

static void __exit unanzacorecleanup(void){
	printk(KERN_ALERT "Cleaning Core0xF0013");	// TEXTO QUE SE MOSTRARA COMO INFORMACION AL USAR ESTA FUNCION
}

module_init(unanzacorestart);		//AQUI INDICAMOS CUAL SERA LA FUNCION QUE SE EJECUTARA MAS AGREGAR EL MODULO
module_exit(unanzacorecleanup);		//AQUI INDICAMOS CUAL SERA LA FUNCION QUE SE EJECUTARA AL ELIMINAR/DESACTIVAR EL MODULO

// A PARTIR DE AQUI, NOS ENCONTRAMOS LA INFORMACION DEL MODULO.

MODULE_LICENSE("GLP");		//LICENCIA DEL MODULO
MODULE_AUTHOR("MANZA");		//AUTOR DEL MODULO
MODULE_DESCRIPTION("VERSION: 0.1 -- DESCRIPTION");	//DESCRIPCION DEL MODULO

